services:
  - type: web
    name: fleet-dashboard-app
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: gunicorn app:app
    plan: free
    envVars:
      - key: FLASK_ENV
        value: production